apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: vendor
  contents:
  - path: gateway-helm
    helmChart:
      name: gateway-helm
      version: v1.2.1
      repository:
        url: oci://docker.io/envoyproxy
- path: helm/envoy-gateway
  contents:
  - path: .
    directory:
      path: vendor/gateway-helm
    ignorePaths:
      - Chart.yaml
