#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) ; readonly dir
cd "${dir}/.."

# Stage 1 sync
set -x
vendir sync
{ set +x; } 2>/dev/null

# Remove trailing whitespace end of lines (hack to fix vendir bug)
find vendor/ -type f -exec sed -i 's/[[:space:]]*$//' {} \;

# Patches
./sync/patches/image-registry/patch.sh
./sync/patches/team-label/patch.sh
./sync/patches/values/patch.sh
./sync/patches/network-policies/patch.sh
./sync/patches/monitoring/patch.sh
./sync/patches/crds/patch.sh
./sync/patches/chart_yaml/patch.sh

HELM_DOCS="docker run --rm -u $(id -u) -v ${PWD}:/helm-docs -w /helm-docs jnorwood/helm-docs:v1.11.0"
$HELM_DOCS --template-files=sync/readme.gotmpl -g helm/envoy-gateway -f values.yaml -o README.md

# Store diffs
rm -f ./diffs/*
for f in $(git --no-pager diff --no-exit-code --no-color --no-index vendor/gateway-helm helm/envoy-gateway --name-only) ; do
        # Skip /dev/null.
        [[ "$f" == "/dev/null" ]] && continue
        # Skip helm/envoy-gateway/Chart.yaml; as we take it as our own.
        [[ "$f" == "helm/envoy-gateway/Chart.yaml" ]] && continue
        [[ "$f" == "helm/envoy-gateway/Chart.lock" ]] && continue
        # Skip helm/envoy-gateway/README.md; as it's autogenerated.
        [[ "$f" == "helm/envoy-gateway/README.md" ]] && continue
        # Skip CRDs
        [[ "$f" =~ ^helm/envoy-gateway/crds/.* ]] && continue
        [[ "$f" =~ ^helm/envoy-gateway/files/.* ]] && continue

        base_file="vendor/gateway-helm/${f#"helm/envoy-gateway/"}"
        [[ ! -e $base_file ]] && base_file="/dev/null"

        set +e
        set -x

        git --no-pager diff --no-exit-code --no-color --no-index "$base_file" "${f}" \
                > "./diffs/${f//\//__}.patch" # ${f//\//__} replaces all "/" with "__"

        { set +x; } 2>/dev/null
        set -e

        ret=$?
        if [ $ret -ne 0 ] && [ $ret -ne 1 ] ; then
                exit $ret
        fi
done
