---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "eg.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: envoy-gateway
    {{- include "eg.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      control-plane: envoy-gateway
      {{- include "eg.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-apiserver
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
  ingress:
    - ports:
        {{- range .Values.deployment.envoyGateway.ports }}
        - port: {{ .port }}
          protocol: TCP
        {{- end }}
      from:
        - namespaceSelector: {}
