apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eg.labels" . | nindent 4 }}
spec:
  endpoints:
  - honorLabels: true
    interval: 60s
    metricRelabelings: []
    path: /metrics
    port: metrics
    relabelings:
    - action: replace
      replacement: ${1}
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{ include "eg.selectorLabels" . | nindent 4 }}

