---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ template "envoy-gateway.fullname" . }}
  namespace: {{ include "envoy-gateway.namespace" . }}
  labels:
    control-plane: envoy-gateway
    {{- include "eg.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      control-plane: envoy-gateway
      {{- include "eg.selectorLabels" . | nindent 6 }}
  egress:
    - toEntities:
        - kube-apiserver
        - cluster
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
  ingress:
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "18000"
              protocol: TCP
            - port: "18001"
              protocol: TCP
            - port: "18002"
              protocol: TCP
            - port: "19001"
              protocol: TCP
