{{- if .Values.deployment.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    {{- include "eg.labels" . | nindent 4 }}
  name: envoy-gateway
  namespace: {{ include "eg.namespace" . }}
spec:
  maxReplicas: {{ .Values.deployment.hpa.maxReplicas }}
  minReplicas: {{ .Values.deployment.hpa.minReplicas }}
  {{- with .Values.deployment.hpa.metrics }}
  metrics:
    {{- toYaml . | nindent 2 }}
  {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: envoy-gateway
{{- end }}