# The global settings for the Envoy Gateway Helm chart.
# These values will be used if the values are not overridden in the other sections.
global:
  images:
    envoyGateway:
      # This is the full image name including the hub, repo, and tag.
      image: docker.io/envoyproxy/gateway:v1.2.1
      # Specify image pull policy if default behavior isn't desired.
      # Default behavior: latest images will be Always else IfNotPresent.
      pullPolicy: IfNotPresent
      # List of secrets in the same namespace of the component that can be used to pull images from private repositories.
      pullSecrets: []
    ratelimit:
      # This is the full image name including the hub, repo, and tag.
      image: "docker.io/envoyproxy/ratelimit:master"
      # Specify image pull policy if default behavior isn't desired.
      # Default behavior: latest images will be Always else IfNotPresent.
      pullPolicy: IfNotPresent
      # List of secrets in the same namespace of the component that can be used to pull images from private repositories.
      pullSecrets: []

name: envoy-gateway
namespace: envoy-gateway-system
serviceType: managed

podDisruptionBudget:
  minAvailable: 0
  # maxUnavailable: 1

image:
  registry: gsoci.azurecr.io
  repository: giantswarm

deployment:
  envoyGateway:
    image:
      name: envoyproxy-gateway
      tag: 'v1.2.1'
    imagePullPolicy: ""
    imagePullSecrets: []
    resources:
      limits:
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 256Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      runAsNonRoot: true
      runAsGroup: 65532
      runAsUser: 65532
      readOnlyRootFilesystem: true
      seccompProfile:
        type: RuntimeDefault
  ports:
    - name: grpc
      port: 18000
      targetPort: 18000
    - name: ratelimit
      port: 18001
      targetPort: 18001
    - name: wasm
      port: 18002
      targetPort: 18002
    - name: metrics
      port: 19001
      targetPort: 19001
  priorityClassName: null
  replicas: 1
  pod:
    affinity: {}
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '19001'
    labels: {}
    topologySpreadConstraints: []
    tolerations: []
    nodeSelector: {}

service:
  annotations: {}

config:
  envoyGateway:
    gateway:
      controllerName: gateway.envoyproxy.io/gatewayclass-controller
    provider:
      type: Kubernetes
    logging:
      level:
        default: info

createNamespace: false

kubernetesClusterDomain: cluster.local

certgen:
  job:
    annotations: {}
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        memory: 500Mi
    affinity: {}
    tolerations: []
    nodeSelector: {}
    ttlSecondsAfterFinished: 30
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsGroup: 65534
      runAsUser: 65534
      seccompProfile:
        type: RuntimeDefault
  rbac:
    annotations: {}
    labels: {}
